    <table id="tableboard" class="display" width="100%" cellspacing="0">
		<thead>
			<tr>
				<th>ID</th>
				<th>date</th>
				<th>Title</th>
				<th>price</th>
				<th>Author</th>
				<th>City</th>
				<th>Category</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<th>ID</th>
				<th>date</th>
				<th>Title</th>
				<th>price</th>
				<th>Author</th>
				<th>City</th>
				<th>Category</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</tfoot>
    <tbody>